name: upcode_ci
description: A collection of tools used by Upcode team
version: 0.9.0
repository: https://github.com/long1eu/upcode_ci
executables:
  upcode:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.1
  pub_semver: ^2.1.0
  googleapis: ^7.0.0
  googleapis_beta: ^7.0.0
  googleapis_auth: ^1.3.0
  uuid: ^3.0.5
  intl: ^0.17.0
  args: ^2.3.0
  xml: ^5.3.1
  http: ^0.13.4
  http_multi_server: ^3.0.1
  xml2json: ^5.3.2
  yaml: ^3.1.0
  protobuf: ^2.0.1
  fixnum: ^1.0.0
  collection: ^1.15.0
  grpc: ^3.0.2
  strings: ^0.2.2
