name: upcode_ci
description: A starting point for Dart libraries or applications.
version: 0.2.3
repository: https://github.com/long1eu/upcode_ci
executables:
  upcode:

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: ^1.7.0
  pub_semver: ^1.4.4
  geodesy: ^0.3.2
  googleapis: ^0.56.1
  googleapis_beta: ^0.51.0
  googleapis_auth: ^0.2.12
  uuid: ^2.2.2
  intl: ^0.16.1
  strings: ^0.1.4
  args: ^1.6.0
  xml: ^4.5.1
  http: ^0.12.2
  http_multi_server: ^2.2.0
  xml2json: ^4.4.0
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.6
  build_runner: ^1.10.6
