name: l10n_generator
description: A sample command-line application.
version: 0.0.1
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.6.0
  collection: ^1.14.13
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
